# Generated by Django 4.2.6 on 2023-10-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=20, verbose_name='ID de Destino')),
                ('city', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=100, verbose_name='Pais')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripcion')),
                ('urlImg', models.ImageField(null=True, upload_to='locations-img', verbose_name='Destinos')),
                ('tipo', models.SmallIntegerField(default=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('fecha_desde', models.DateField(null=True, verbose_name='Fecha Desde')),
                ('fecha_hasta', models.DateField(null=True, verbose_name='Fecha hasta')),
                ('valor', models.FloatField(default=0, verbose_name='valor')),
                ('pasajeros', models.SmallIntegerField(default=1, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Usertravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.travel')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='travel',
            name='usuarios',
            field=models.ManyToManyField(through='core.Usertravel', to='core.usuario', verbose_name='usuarios'),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('lastname', models.CharField(max_length=20, verbose_name='Apellido')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Email')),
            ],
        ),
    ]
