# Generated by Django 4.2.6 on 2023-11-12 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=20, verbose_name='ID de Destino')),
                ('city', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=100, verbose_name='Pais')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripcion')),
                ('urlImg', models.ImageField(null=True, upload_to='locations-img', verbose_name='Destinos')),
                ('tipo', models.CharField(choices=[('1', 'Elegidos'), ('2', 'Recomendados'), ('3', 'inactivo')], default=1, max_length=1, verbose_name='Estado')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(null=True, verbose_name='Fecha Desde')),
                ('fecha_hasta', models.DateField(null=True, verbose_name='Fecha hasta')),
                ('valor', models.FloatField(default=0, verbose_name='valor')),
                ('pasajeros', models.SmallIntegerField(default=1, verbose_name='pasajeros')),
            ],
        ),
        migrations.CreateModel(
            name='Usertravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.travel', verbose_name='Travel')),
                ('usuarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Traveldestinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.destinos', verbose_name='Usuario')),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.travel', verbose_name='Travel')),
            ],
        ),
        migrations.AddField(
            model_name='travel',
            name='destino',
            field=models.ManyToManyField(blank=True, through='core.Traveldestinos', to='core.destinos', verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='travel',
            name='usuarios',
            field=models.ManyToManyField(blank=True, through='core.Usertravel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('lastname', models.CharField(max_length=20, verbose_name='Apellido')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Email')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
