# Generated by Django 4.2.6 on 2023-10-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterModelOptions(
            name='destinos',
            options={'ordering': ['city']},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ['destino']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.usuario', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='tipo',
            field=models.CharField(choices=[('1', 'Elegidos'), ('2', 'Recomendados'), ('3', 'inactivo')], default=1, max_length=1, verbose_name='Estado'),
        ),
    ]
