# Generated by Django 4.2.6 on 2023-10-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('urlImg', models.ImageField(null=True, upload_to='images/locations-img/', verbose_name='Destinos')),
                ('activo', models.BooleanField(verbose_name='Estado')),
                ('tipo', models.BooleanField(verbose_name='Tipo')),
            ],
        ),
    ]
