# Generated by Django 4.2.6 on 2023-11-26 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_contacto_email_remove_travel_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripcion')),
                ('valor', models.FloatField(default=0, verbose_name='valor')),
                ('tipo', models.CharField(default=1, max_length=1, verbose_name='Estado')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Excursiontravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursiones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.excursiones', verbose_name='Excursiones')),
            ],
        ),
        migrations.RemoveField(
            model_name='travel',
            name='usuarios',
        ),
        migrations.DeleteModel(
            name='Usertravel',
        ),
        migrations.AddField(
            model_name='excursiontravel',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.travel', verbose_name='Travel'),
        ),
        migrations.AddField(
            model_name='travel',
            name='excursiones',
            field=models.ManyToManyField(blank=True, through='core.Excursiontravel', to='core.excursiones', verbose_name='Excursion'),
        ),
        migrations.AddField(
            model_name='travel',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
