# Generated by Django 4.2.6 on 2023-10-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_destinos_id_alter_destinos_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinos',
            name='urlImg',
            field=models.FileField(null=True, upload_to='static/core/images/locations-img/', verbose_name='Destinos'),
        ),
    ]
