# Generated by Django 4.2.6 on 2023-10-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_destinos_urlimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinos',
            name='urlImg',
            field=models.ImageField(null=True, upload_to='locations-img', verbose_name='Destinos'),
        ),
    ]
